:icons: font

= Continuous Delivery

== Introduction

The most important problem that we face as software professionals is this: How we deliver to users as quicly as possible?
_Development pipeline_ is, in essence, an automated implementation of your application's build, deploy, test and releases process.
The aim in the deployment pipe line is to make every part of the process if building, deploying, testing, and relasing software visible to everybody involved, aiding collaboration, it improves feedback so that problems are identified, and so resolved, as early in the process as possible, finally it enables teams to deploy and release any version of their software to any environment at will through a fully automated process.

TIP: So while it is important to deliver our software as quickly as possible, it is essential to maintain an appropiate level of quality.

== Every change should trigger the feedback process

A working software application can be usefull decomposed into four components: excecutable code, configuration, host environment, and data. If any of them changes, it can lead to a change in the behaviour of the application. Therefore we need to keep all four fo these components under control and ensure that a change in any of them is verified.

* The process of creating the executable code must work.
* The software's unit test must pass.
* The software should fulfill certain quiality criteria such as test coverage and other technology-specific metrics.
* The software's functional acceptance test must pass.
* The software's nonfunctional test must pass.
* The software must go through exploratory testing and a demosntration to the customer and a selection of users.
