= Spring Boot with Jade

== Setup

We are going to create a basic project with Spring Boot and Jade. First we need to go to this site: link:http://start.spring.io/[Spring Initializr] and create a new project with next elements:

* Type: Gradle Project
* Java version: 1.8
* Language: Groovy
* Packaging: Jar
* Dependencies:
** Web
** JPA
** H2
** Actuator

Next download your project, and unzip it in some directory that you want. Browse that directory and you should see the following structure:

----
.
│── build.gradle
└── src
   ├── main
   │   ├── groovy
   │   │   └── jade
   │   │       └── JadeApplication.groovy
   │   └── resources
   │       ├── application.properties
   │       ├── static
   │       └── templates
   └── test
       └── groovy
           └── jade
               └── JadeApplicationTests.groovy
----

You should see your gradle file as follow:

----
buildscript {
  ext {
    springBootVersion = '1.3.0.M2'
  }
  repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/snapshot" }
    maven { url "https://repo.spring.io/milestone" }
  }
  dependencies {
    classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
  }
}

apply plugin: 'groovy'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'spring-boot'

jar {
  baseName = 'spring'
  version = '0.0.1-SNAPSHOT'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
  mavenCentral()
  maven { url "https://repo.spring.io/snapshot" }
  maven { url "https://repo.spring.io/milestone" }
}


dependencies {
  compile("org.springframework.boot:spring-boot-starter-actuator")
  compile("org.springframework.boot:spring-boot-starter-data-jpa")
  compile("org.springframework.boot:spring-boot-starter-web")
  compile("org.codehaus.groovy:groovy")
  runtime("com.h2database:h2")
  testCompile("org.springframework.boot:spring-boot-starter-test")
}

eclipse {
  classpath {
    containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
    containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
    }
}

task wrapper(type: Wrapper) {
  gradleVersion = '2.3'
}
----

As you can see we have Spring boot 1.3.0.M2, with Groovy plugin, and dependencies such as actuator, data JPA, web, H2 database and boot starter testing framework.

Type in your command line:

----
gradle build
----

Go to the project home and you should see the following path there build/libs, run the jar file as follow:

----
java -jar spring-boot-jade-0.0.1-SNAPSHOT.jar
----

At this point you have an application Spring Boot running in 8080 port.
